<?php

class MBeneficioRM extends ModelRM  {

	/**
	* Busca centros de custos por uma lista de chapas
	*/
	public function buscaCentrosDeCustosPorChapas($chapas) {

		$where = "('".$chapas."')";

		$query ="SELECT
						CODCOLIGADA as codcoligada,
						CHAPA AS chapa,
						CODCCUSTO AS 'centroCusto',
						VALOR AS 'porcentagem',
						NULL AS chapas
						FROM
							dbo.PFRATEIOFIXO
							WHERE CHAPA IN {$where}
						";

		$result = $this->execute($query);

		return $result;
	}


	/**
	* Busca centros de custos por uma chapa unica
	*/
	public function buscaCentrosDeCustosPorChapa($chapa) {


		$query ="SELECT
						CODCOLIGADA as codcoligada,
						CHAPA AS chapa,
						CODCCUSTO AS 'centroCusto',
						VALOR AS 'porcentagem',
						NULL AS chapas
						FROM
							dbo.PFRATEIOFIXO
							WHERE CHAPA = {$chapa}
						";

		$result = $this->execute($query);

		return $result;
	}


	/**
	* Busca dados detalhados do usuario no RM
	*/
	public function buscarDadosDetalhadosFuncionario($codColigada = 2, $chapa){

		$query = " SELECT
					PFUNC.SALARIO
				FROM
					PFUNC (NOLOCK)
				JOIN PPESSOA (NOLOCK) ON PPESSOA.CODIGO = PFUNC.CODPESSOA

				LEFT JOIN PFHSTAFT H WITH(NOLOCK) ON
					    (PFUNC.CODCOLIGADA = H.CODCOLIGADA AND PFUNC.CHAPA = H.CHAPA
					            AND H.DTINICIO = (SELECT MAX(DTINICIO) FROM PFHSTAFT HF WITH(NOLOCK) WHERE PFUNC.CODCOLIGADA = HF.CODCOLIGADA AND PFUNC.CHAPA = HF.CHAPA AND H.CODCOLIGADA = HF.CODCOLIGADA  ))

				LEFT JOIN GMUNICIPIO (NOLOCK) ON (
					(
						GMUNICIPIO.CODMUNICIPIO = PPESSOA.CODMUNICIPIO
					)
					OR (
						GMUNICIPIO.NOMEMUNICIPIO = PPESSOA.CIDADE
					)
				)
				AND GMUNICIPIO.CODETDMUNICIPIO = PPESSOA.ESTADO
				LEFT JOIN GETD (NOLOCK) ON GETD.CODETD = GMUNICIPIO.CODETDMUNICIPIO
				AND GETD.IDPAIS = 1
				LEFT JOIN DCODIFICACAOMUNICIPIO AS IBGE (NOLOCK) ON IBGE.CODMUNICIPIO = GMUNICIPIO.CODMUNICIPIO
				AND IBGE.CODETDMUNICIPIO = GMUNICIPIO.CODETDMUNICIPIO
				AND IBGE.IDCLASSIFMUNICIPIO = 1
				LEFT JOIN DCODIFICACAOMUNICIPIO AS CORREIOS (NOLOCK) ON CORREIOS.CODMUNICIPIO = GMUNICIPIO.CODMUNICIPIO
				AND CORREIOS.CODETDMUNICIPIO = GMUNICIPIO.CODETDMUNICIPIO
				AND CORREIOS.IDCLASSIFMUNICIPIO = 20
				JOIN PSECAO (NOLOCK) ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA
				AND PSECAO.CODIGO = PFUNC.CODSECAO
				JOIN GFILIAL (NOLOCK) ON GFILIAL.CODCOLIGADA = PSECAO.CODCOLIGADA
				AND GFILIAL.CODFILIAL = PSECAO.CODFILIAL
				JOIN GCOLIGADA (NOLOCK) ON GCOLIGADA.CODCOLIGADA = GFILIAL.CODCOLIGADA
				AND GCOLIGADA.ATIVO = 'T'
				JOIN PFUNCAO (NOLOCK) ON PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA
				AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO
				JOIN PCARGO (NOLOCK) ON PCARGO.CODCOLIGADA = PFUNCAO.CODCOLIGADA
				AND PCARGO.CODIGO = PFUNCAO.CARGO

				WHERE
					(	CONVERT (
							VARCHAR (10),
							PFUNC.CODCOLIGADA
						) = {$codColigada}
					)
				AND
					PFUNC.CHAPA = {$chapa}";

		$result = $this->execute($query);
		return $result;
	}


	/**
	* Busca dados detalhados do usuario no RM
	*/
	public function buscarDadosDetalhadosFuncionarioColigada($codColigada = 2, $chapaDiretor = null){

		$query = " SELECT
					PFUNC.CHAPA,
					PFUNC.SALARIO,
					ZVTLMHIERARQUIAFUNC.CHAPADIRETOR
				FROM
					PFUNC (NOLOCK)
				JOIN PPESSOA (NOLOCK) ON PPESSOA.CODIGO = PFUNC.CODPESSOA

				LEFT JOIN PFHSTAFT H WITH(NOLOCK) ON
					    (PFUNC.CODCOLIGADA = H.CODCOLIGADA AND PFUNC.CHAPA = H.CHAPA
					            AND H.DTINICIO = (SELECT MAX(DTINICIO) FROM PFHSTAFT HF WITH(NOLOCK) WHERE PFUNC.CODCOLIGADA = HF.CODCOLIGADA AND PFUNC.CHAPA = HF.CHAPA AND H.CODCOLIGADA = HF.CODCOLIGADA  ))

				LEFT JOIN GMUNICIPIO (NOLOCK) ON (
					(
						GMUNICIPIO.CODMUNICIPIO = PPESSOA.CODMUNICIPIO
					)
					OR (
						GMUNICIPIO.NOMEMUNICIPIO = PPESSOA.CIDADE
					)
				)
				AND GMUNICIPIO.CODETDMUNICIPIO = PPESSOA.ESTADO
				LEFT JOIN GETD (NOLOCK) ON GETD.CODETD = GMUNICIPIO.CODETDMUNICIPIO
				AND GETD.IDPAIS = 1
				LEFT JOIN DCODIFICACAOMUNICIPIO AS IBGE (NOLOCK) ON IBGE.CODMUNICIPIO = GMUNICIPIO.CODMUNICIPIO
				AND IBGE.CODETDMUNICIPIO = GMUNICIPIO.CODETDMUNICIPIO
				AND IBGE.IDCLASSIFMUNICIPIO = 1
				LEFT JOIN DCODIFICACAOMUNICIPIO AS CORREIOS (NOLOCK) ON CORREIOS.CODMUNICIPIO = GMUNICIPIO.CODMUNICIPIO
				AND CORREIOS.CODETDMUNICIPIO = GMUNICIPIO.CODETDMUNICIPIO
				AND CORREIOS.IDCLASSIFMUNICIPIO = 20
				JOIN PSECAO (NOLOCK) ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA
				AND PSECAO.CODIGO = PFUNC.CODSECAO
				JOIN GFILIAL (NOLOCK) ON GFILIAL.CODCOLIGADA = PSECAO.CODCOLIGADA
				AND GFILIAL.CODFILIAL = PSECAO.CODFILIAL
				JOIN GCOLIGADA (NOLOCK) ON GCOLIGADA.CODCOLIGADA = GFILIAL.CODCOLIGADA
				AND GCOLIGADA.ATIVO = 'T'
				JOIN PFUNCAO (NOLOCK) ON PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA
				AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO
				JOIN PCARGO (NOLOCK) ON PCARGO.CODCOLIGADA = PFUNCAO.CODCOLIGADA
				AND PCARGO.CODIGO = PFUNCAO.CARGO
				JOIN ZVTLMHIERARQUIAFUNC (NOLOCK) ON PFUNC.CODCOLIGADA = ZVTLMHIERARQUIAFUNC.CODCOLIGADA
				AND PFUNC.CHAPA = ZVTLMHIERARQUIAFUNC.CHAPA

				WHERE
					(	CONVERT (
							VARCHAR (10),
							PFUNC.CODCOLIGADA
						) = {$codColigada}
					)

				    AND PFUNC.CODSITUACAO NOT IN ('D','I','C', 'Z')
					AND PFUNC.CODTIPO NOT IN ('Z', 'T')

				";

			if ($chapaDiretor != null) {

				$query .= " AND ZVTLMHIERARQUIAFUNC.CHAPADIRETOR = {$chapaDiretor}";
			}



		$result = $this->execute($query);

		foreach($result as $row) {
			$retorno[$row->CHAPA]['SALARIO'] = $row->SALARIO;
			$retorno[$row->CHAPA]['CHAPADIRETOR'] = $row->CHAPADIRETOR;
		}
		return $retorno;
	}

	/**
	* Busca getentes
	*/
	public function buscarHierarquiaLideres($listaFiliais, $filial = null, $diretor = null) {


		$query ="

				SELECT
				    PFUNC.CODCOLIGADA AS 'codColigada',
				    PFUNC.CHAPA AS 'chapaFuncionario',
				    PFUNC.NOME AS 'nomeFuncionario',
				    PFUNC.CODFILIAL AS 'filial',
				    PFUNCAO.NOME AS 'funcao',
				    PPESSOA.EMAIL AS 'email',
				    GFILIAL.ESTADO AS 'estado',
				    GFILIAL.NOMEFANTASIA AS 'nomeFilial',
					HIERARQUIA.CHAPADIRETOR AS 'chapaDiretor'

				FROM ZVTLMHIERARQUIAFUNC AS HIERARQUIA (NOLOCK)
				INNER JOIN PFUNC (NOLOCK)
				    ON PFUNC.CODCOLIGADA = HIERARQUIA.CODCOLIGADA
				    AND PFUNC.CHAPA = HIERARQUIA.CHAPA
				INNER JOIN PFUNCAO (NOLOCK)
				    ON PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA
				    AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO
				INNER JOIN PPESSOA (NOLOCK)
				    ON PPESSOA.CODIGO = PFUNC.CODPESSOA
				INNER JOIN GFILIAL (NOLOCK)
				    ON GFILIAL.CODCOLIGADA = PFUNC.CODCOLIGADA
				    AND GFILIAL.CODFILIAL = PFUNC.CODFILIAL
				WHERE HIERARQUIA.IDNIVELHIERARQUIA = 3";

				if ($filial != null) {

					$query .= " AND PFUNC.CODFILIAL = {$filial}";
				} else {
					$query .= " AND PFUNC.CODFILIAL IN ({$listaFiliais})";
				}

				if ($diretor != null) {

					$query .= " AND HIERARQUIA.CHAPADIRETOR = {$diretor}";
				}

				$query .=" ORDER BY PFUNC.NOME
				";

		$result = $this->execute($query);

		return $result;
	}

	/**
	* Busca diretores
	*/
	public function buscarDiretores($listaFiliais, $filial = null) {


		$query ="

				SELECT
				    PFUNC.CODCOLIGADA AS 'codColigada',
				    PFUNC.CHAPA AS 'chapaFuncionario',
				    PFUNC.NOME AS 'nomeFuncionario',
				    PFUNC.CODFILIAL AS 'filial',
				    PFUNCAO.NOME AS 'funcao',
				    PPESSOA.EMAIL AS 'email',
				    GFILIAL.ESTADO AS 'estado',
				    GFILIAL.NOMEFANTASIA AS 'nomeFilial'

				FROM ZVTLMHIERARQUIAFUNC AS HIERARQUIA (NOLOCK)
				INNER JOIN PFUNC (NOLOCK)
				    ON PFUNC.CODCOLIGADA = HIERARQUIA.CODCOLIGADA
				    AND PFUNC.CHAPA = HIERARQUIA.CHAPA
				INNER JOIN PFUNCAO (NOLOCK)
				    ON PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA
				    AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO
				INNER JOIN PPESSOA (NOLOCK)
				    ON PPESSOA.CODIGO = PFUNC.CODPESSOA
				INNER JOIN GFILIAL (NOLOCK)
				    ON GFILIAL.CODCOLIGADA = PFUNC.CODCOLIGADA
				    AND GFILIAL.CODFILIAL = PFUNC.CODFILIAL
				WHERE HIERARQUIA.IDNIVELHIERARQUIA = 2";

				if ($filial != null) {

					$query .= " AND PFUNC.CODFILIAL = {$filial}";
				} else {
					$query .= " AND PFUNC.CODFILIAL IN ({$listaFiliais})";
				}
				$query .=" ORDER BY PFUNC.NOME
				";

		$result = $this->execute($query);

		return $result;
	}

	public function buscarSecaoFuncaoVinculada($chapa, $codColigada = 2) {

		$query = "	SELECT
						PFUNC.CODSECAO AS 'codSecao'
					FROM PFUNC (NOLOCK)
					INNER JOIN PFRATEIOFIXO RAT (NOLOCK)
						ON RAT.CODCOLIGADA = PFUNC.CODCOLIGADA
						AND RAT.CHAPA = PFUNC.CHAPA
					INNER JOIN PSECAO AS CC (NOLOCK)
						ON CC.CODIGO LIKE REPLACE(RAT.CODCCUSTO, '.000', '') + '%'
						AND CC.CODCOLIGADA = PFUNC.CODCOLIGADA
						AND LEN(CC.CODIGO) >= 23
					LEFT JOIN VLOTACAO AS LOT (NOLOCK)
						ON LOT.CODSECAO = CC.CODIGO
						AND LOT.CODCOLIGADA =  CC.CODCOLIGADA
					LEFT JOIN VTABELASALARIAL AS SAL (NOLOCK)
						ON SAL.CODCOLIGADA = CC.CODCOLIGADA
						AND SAL.CODTABELA = LOT.CODTABELA
						AND SAL.NIVEL = LOT.CODFUNCAO
						AND SAL.FAIXA = '001'
					LEFT JOIN PFUNCAO (NOLOCK)
						ON PFUNCAO.CODIGO = LOT.CODFUNCAO
						AND PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA
					LEFT JOIN GFILIAL (NOLOCK)
						ON GFILIAL.CODFILIAL = CC.CODFILIAL
						AND GFILIAL.CODCOLIGADA = CC.CODCOLIGADA
					WHERE PFUNC.CHAPA = '{$chapa}'
					AND PFUNC.CODCOLIGADA = {$codColigada}
					AND PFUNCAO.INATIVA NOT IN (1, '1')

					GROUP BY PFUNC.CODSECAO
					";

		$result = $this->execute($query);
		return $result;
	}

	public function buscarFiliaisAtivas(){
		$query ="
					SELECT
						Z.CODFILIAL AS 'idFilial',
						G.NOMEFANTASIA AS 'filial',
						G.ESTADO AS 'estado'
					FROM ZMDFILIALREG AS Z
					INNER JOIN GFILIAL G ON G.CODCOLIGADA = Z.CODCOLIGADA AND G.CODFILIAL = Z.CODFILIAL
					WHERE INATIVA = 0
				";

		$result = $this->execute($query);

		return $result;
	}
}